"""Seed a 50-task x 3-model load run and report wall-clock time and throughput.

Usage:
    EVAL_API_URL=http://localhost:8000 python scripts/seed_and_run.py

The run executes against FakeProvider (no API key required) via the Celery
worker; this script only drives the HTTP API and polls for completion.
"""

import asyncio
import os
import sys
import time

import httpx

API_URL = os.environ.get("EVAL_API_URL", "http://localhost:8000")
NUM_TASKS = 50
NUM_MODELS = 3
TERMINAL_STATUSES = {"completed", "failed", "cancelled"}
POLL_TIMEOUT_SECONDS = 300


async def _seed(client: httpx.AsyncClient) -> tuple[str, list[str]]:
    response = await client.post(
        "/v1/task-sets",
        json={
            "name": f"load-test-{int(time.time())}",
            "description": "generated by scripts/seed_and_run.py",
        },
    )
    response.raise_for_status()
    task_set_id = response.json()["id"]

    async def create_task(i: int) -> None:
        r = await client.post(
            f"/v1/task-sets/{task_set_id}/tasks",
            json={
                "prompt": f"Load-test prompt number {i}: answer concisely.",
                "capability": "load_test",
                "grader_type": "exact_match",
            },
        )
        r.raise_for_status()

    await asyncio.gather(*(create_task(i) for i in range(NUM_TASKS)))

    async def create_model(j: int) -> str:
        r = await client.post(
            "/v1/models",
            json={
                "name": f"fake-model-{j}",
                "provider": "local",
                "model_id": f"fake-model-{j}",
                "model_version": "v1",
            },
        )
        r.raise_for_status()
        return r.json()["id"]

    model_ids = list(await asyncio.gather(*(create_model(j) for j in range(NUM_MODELS))))
    return task_set_id, model_ids


async def main() -> None:
    print(f"=== llm-eval-harness load test ===\napi: {API_URL}")
    async with httpx.AsyncClient(base_url=API_URL, timeout=30.0) as client:
        health = await client.get("/healthz")
        health.raise_for_status()

        task_set_id, model_ids = await _seed(client)
        print(
            f"seeded task set {task_set_id} with {NUM_TASKS} tasks and {NUM_MODELS} model endpoints"
        )

        total_items = NUM_TASKS * NUM_MODELS
        start = time.perf_counter()
        response = await client.post(
            "/v1/eval-runs",
            json={"task_set_id": task_set_id, "model_endpoint_ids": model_ids},
        )
        response.raise_for_status()
        run_id = response.json()["id"]
        print(f"submitted eval run {run_id} ({total_items} run items)")

        body: dict | None = None
        while True:
            await asyncio.sleep(0.25)
            r = await client.get(f"/v1/eval-runs/{run_id}")
            r.raise_for_status()
            body = r.json()
            if body["status"] in TERMINAL_STATUSES:
                break
            if time.perf_counter() - start > POLL_TIMEOUT_SECONDS:
                print("timed out waiting for eval run completion", file=sys.stderr)
                sys.exit(1)

        assert body is not None
        elapsed = time.perf_counter() - start
        throughput = total_items / elapsed if elapsed > 0 else float("inf")

        print(f"\neval run {run_id} finished with status={body['status']}")
        print(f"wall clock: {elapsed:.2f}s")
        print(f"throughput: {throughput:.1f} items/s")
        print("per-model aggregates:")
        for model in body["models"]:
            counts = model["counts"]
            print(
                f"  {model['name']}: succeeded={counts['succeeded']} "
                f"failed={counts['failed']} dead_lettered={counts['dead_lettered']} "
                f"mean_latency_ms={model['mean_latency_ms']} "
                f"cost=${model['total_cost_usd']:.6f}"
            )


if __name__ == "__main__":
    asyncio.run(main())
